services:

  # sensor:
  #   container_name: maltrail-sensor
  #   build: .
  #   command: sensor.py
  #   restart: unless-stopped
  #   network_mode: host
  #   privileged: true
  #   volumes:
  #     - "/etc/localtime:/etc/localtime:ro"
  #     - "/etc/maltrail.conf:/opt/maltrail/maltrail.conf:ro"
  #     - "/var/log/maltrail:/var/log/maltrail"
    
  server:
    container_name: maltrail-server
    build: .
    command: server.py
    restart: unless-stopped
    ports:
      - "8338:8338/tcp"
      - "8337:8337/udp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/maltrail.conf:/opt/maltrail/maltrail.conf:ro"
      - "/var/log/maltrail:/var/log/maltrail"
